version: "3.8"

services:
  caddy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.entrypoints=http"
      - "traefik.http.routers.my-router.rule=Host(`my-project.test`)"
    image: caddy:2-alpine
    expose:
      - 80
      - 443
    volumes:
      - ./.docker/server/Caddyfile:/etc/caddy/Caddyfile:ro
      - .:/var/www/html:delegated
    restart: unless-stopped
    networks:
      - web

  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.entrypoints=http"
      - "traefik.http.routers.my-router.rule=Host(`my-project.test`)"
    image: nginx:1-alpine
    expose:
      - 80
      - 443
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/server/conf.d:/etc/nginx/conf.d:ro
      - .:/var/www/html:delegated
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
