version: "3.8"

services:
  app:
    image: ghcr.io/josepostiga/infrastructure/php:8.1-dev-fpm
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    expose:
      - 9000

  scheduler:
    image: ghcr.io/josepostiga/infrastructure/php:8.1-prod-fpm
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    entrypoint: ./.docker/scheduler/entrypoint.sh
