version: "3.8"

services:
  mailhog:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.entrypoints=http"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.test`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    image: mailhog/mailhog:latest
    pull_policy: always
    expose:
      - 1025
      - 8025
    volumes:
      - mailhog_data:/maildir
    environment:
      MH_STORAGE: maildir
    restart: unless-stopped
    networks:
      - web

volumes:
  mailhog_data:

networks:
  web:
    external: true
